OnlineShop.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Data;
using OnlineShop.Data.Models;
using OnlineShop.Web.ViewModels.Order;
using System.Security.Claims;
using OnlineShop.Web.ViewModels.Transaction;
using iTextSharp.text.pdf;
using iTextSharp.text;
using Microsoft.AspNetCore.Authorization;
using iTextSharp.text.pdf.draw;
using OnlineShop.Data.Models.Enums.Payment;
using OnlineShop.Services.Data.Interfaces;
using Stripe.Checkout;
using System.Linq;

namespace OnlineShop.Web.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IConfiguration _configuration;

        public OrderController(IOrderService orderService, IConfiguration configuration)
        {
            _orderService = orderService;
            _configuration = configuration;
        }

        [HttpPost]
        public async Task<IActionResult> CreateCheckoutSession(int orderId)
        {
            var order = await _orderService.GetOrderDetails(orderId);
            if (order == null)
            {
                return NotFound();
            }

            var request = HttpContext.Request;
            var domain = $"{request.Scheme}://{request.Host}";

            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string> { "card" },
                Mode = "payment",
                LineItems = order.OrderProducts.Select(item => new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        Currency = "usd",
                        UnitAmount = (long)(item.UnitPrice * 100),
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.ProductName,
                            Images = new List<string> {item.ImgUrl}
                        },
                    },
                    Quantity = item.Quantity,
                }).ToList(),
                SuccessUrl = $"{domain}/Order/CheckoutSuccess?orderId={orderId}&session_id={{CHECKOUT_SESSION_ID}}",
                CancelUrl = $"{domain}/Order/CheckoutCancel?orderId={orderId}",
            };

            var service = new SessionService();
            Session session = await service.CreateAsync(options);

            return Json(new { sessionId = session.Id });
        }

        public async Task<IActionResult> CheckoutSuccess(int orderId)
        {
            try
            {
                var success = await _orderService.FinalizeOrder(orderId);
                if (!success)
                {
                    TempData["ErrorMessage"] = "Payment was processed but there was an issue finalizing the order.";
                }
                else
                {
                    TempData["SuccessMessage"] = "Payment successful and order finalized!";
                }
                return RedirectToAction("Details", new { id = orderId });
            }
            catch (Exception ex)
            {
                return Content($"An error occurred during CheckoutSuccess: {ex.Message}");
            }
        }

        public IActionResult CheckoutCancel(int orderId)
        {
            TempData["ErrorMessage"] = "Payment cancelled. Please try again.";
            return RedirectToAction("Details", new { id = orderId });
        }

        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var orders = await _orderService.GetAllOrdersForUser(userId);

            return View(orders.ToList());
        }


        public async Task<IActionResult> Details(int id)
        {
            var orderDetails = await _orderService.GetOrderDetails(id);

            if (orderDetails == null)
            {
                return NotFound();
            }

            ViewBag.StripePublishableKey = _configuration["Stripe:PublishableKey"];
            return View(orderDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Cancel(int id)
        {
            var success = await _orderService.CancelOrder(id);

            if (!success)
            {
                return NotFound();
            }


            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> FinalizeOrder(int id)
        {
            var success = await _orderService.FinalizeOrder(id);

            if (!success)
            {
                TempData["ErrorMessage"] = "Insufficient stock for one or more products in the order.";
                return RedirectToAction("Details", new { id });
            }

            TempData["SuccessMessage"] = "Thank you for your order! Your order has been finalized. \u2705";

            return RedirectToAction("Details", new { id });
        }


        public async Task<IActionResult> TransactionHistory(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var viewModel = await _orderService.GetTransactionHistoryAsync(id, userId);

            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public async Task<IActionResult> ExportToPdf(int orderId)
        {
            var pdfBytes = await _orderService.GenerateOrderTransactionPdfAsync(orderId);

            if (pdfBytes == null)
            {
                return NotFound();
            }

            var fileName = $"TransactionHistory_{orderId}.pdf";
            return File(pdfBytes, "application/pdf", fileName);
        }
    }
}

OnlineShop.Web/Controllers/ProductController.cs
using System.Security.Claims;
using iTextSharp.text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Data;
using OnlineShop.Data.Models;
using OnlineShop.Services.Data.Interfaces;
using OnlineShop.Web.ViewModels.Product;
using X.PagedList.Extensions;


namespace OnlineShop.Web.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IProductService _productService;
        private readonly IProductWishlistService _productWishlistService;
        private readonly ApplicationDbContext _context;
        private const int pageSize = 6;

        public ProductController(
            UserManager<ApplicationUser> userManager,
            IProductService productService,
            IProductWishlistService productWishlistService,
            ApplicationDbContext context
            )
        {
            _userManager = userManager;
            _productService = productService;
            _productWishlistService = productWishlistService;
            _context = context;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index(
            int? genderId,
            int? clothingTypeId,
            int? minPrice,
            int? maxPrice,
            List<int>? sizeIds,
            string searchTerm,
            bool? isOnSale,
            string sortOrder,
            int page = 1)
        {
            int? sanitizedMinPrice = minPrice;
            int? sanitizedMaxPrice = maxPrice;

            if (sanitizedMinPrice < 0) sanitizedMinPrice = null;
            if (sanitizedMaxPrice < 0) sanitizedMaxPrice = null;

            if (sanitizedMinPrice.HasValue && sanitizedMaxPrice.HasValue && sanitizedMinPrice > sanitizedMaxPrice)
            {
                (sanitizedMaxPrice, sanitizedMinPrice) = (sanitizedMinPrice, sanitizedMaxPrice);
            }


            var products = await _productService.GetProductsAsync(
                genderId,
                clothingTypeId,
                searchTerm,
                sanitizedMinPrice,
                sanitizedMaxPrice,
                sizeIds,
                isOnSale,
                sortOrder);

            var userId = GetUserId();
            var wishlist = await _productWishlistService.GetUserWishlistAsync(userId!);
            var wishlistProductIds = wishlist.Select(p => p.ProductId).ToList();

            var pagedProducts = products.ToPagedList(page, pageSize);

            ViewBag.GenderCounts = await _productService.GetGenderCountsAsync(
                clothingTypeId,
                minPrice,
                maxPrice,
                searchTerm
            );

            ViewBag.ClothingTypeCounts = await _productService.GetClothingTypeCountsAsync(
                genderId,
                minPrice,
                maxPrice,
                searchTerm
            );

            var sizes = await _context.Sizes.ToListAsync();

            ViewBag.WishlistProductIds = wishlistProductIds;
            ViewBag.GenderId = genderId;
            ViewBag.ClothingTypeId = clothingTypeId;
            ViewBag.MinPrice = sanitizedMinPrice;
            ViewBag.MaxPrice = sanitizedMaxPrice;
            ViewBag.Sizes = sizes;
            ViewBag.IsOnSale = isOnSale ?? false;
            ViewBag.SortOrder = sortOrder;

            return View(pagedProducts);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var userId = _userManager.GetUserId(User);
            var product = await _productService.GetEditProductViewModelAsync(id, userId!);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductEditViewModel model)
        {
            if (id != model.Id)
            {
                return BadRequest();
            }

            ModelState.Remove(nameof(model.Genders));
            ModelState.Remove(nameof(model.ClothingTypes));

            if (!ModelState.IsValid)
            {
                model.Genders = await _productService.GetGendersAsync();
                model.ClothingTypes = await _productService.GetClothingTypesAsync();
                return View(model);
            }

            var userId = _userManager.GetUserId(User);

            var success = await _productService.UpdateProductAsync(model, userId);

            if (!success)
            {
                return Forbid();
            }

            return RedirectToAction("Details", new { id = model.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitReview(int productId, int rating, string comment)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            await _productService.SubmitReview(productId, userId, rating, comment);

            return RedirectToAction("Details", new { id = productId });
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var productDetails = await _productService.ViewDetailsAboutProductAsync(id, userId);

            if (productDetails == null)
            {
                return NotFound();
            }

            return View(productDetails);
        }

        public string? GetUserId()
        {
            return User.FindFirstValue(ClaimTypes.NameIdentifier);
        }
    }
}

OnlineShop.Web/Controllers/WishlistController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Services.Data.Interfaces;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using X.PagedList.Extensions;

namespace OnlineShop.Web.Controllers
{
    [Authorize]
    public class WishlistController : Controller
    {
        private readonly IProductWishlistService _wishlistService;
        public WishlistController(IProductWishlistService wishlistService)
        {
            _wishlistService = wishlistService;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            var userId = GetUserId();
            int pageSize = 4;

            var wishlistItems = await _wishlistService.GetUserWishlistAsync(userId);
            var pagedWishlistItems = wishlistItems.ToPagedList(page, pageSize);

            return View(pagedWishlistItems);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToWishlist(int productId)
        {
            var userId = GetUserId();
            var success = await _wishlistService.AddToWishlistAsync(userId, productId);

            if (success)
            {
                TempData["SuccessMessage"] = "Product added to wishlist!";
            }
            else
            {
                TempData["ErrorMessage"] = "Product is already in your wishlist!";
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromWishlist(int wishlistProductId)
        {
            var userId = GetUserId();
            var result = await _wishlistService.RemoveFromWishlistAsync(userId, wishlistProductId);

            if (result)
            {
                TempData["SuccessMessage"] = "Product removed from wishlist!";
            }
            else
            {
                TempData["ErrorMessage"] = "Product not found in your wishlist!";
            }

            return RedirectToAction("Index");
        }

        private string? GetUserId()
        {
            return User.FindFirstValue(ClaimTypes.NameIdentifier);
        }
    }
}

OnlineShop.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using OnlineShop.Data.Models
@using static OnlineShop.Common.ApplicationConstants
@inject SignInManager<ApplicationUser> SignInManager
@{
    int currentYear = DateTime.UtcNow.Year;
    string footerYear = (ReleaseYear == currentYear) ? $"{currentYear}" : $"{ReleaseYear} - {currentYear}";
}

@using OnlineShop.Web.Resources

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="/images/FashionShopLogo.ico" rel="icon" type="image/x-icon" />
    <title>@ViewData["Title"] - FashionShop</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <img src="~/images/logo.png" class="img-fluid" style="max-width: 80px;">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link ms-3" asp-area="" asp-controller="Home" asp-action="Index">@Resource.Home <i class="fa-solid fa-house"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">@Resource.Products <i class="fa-solid fa-shirt"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ShoppingCart" asp-action="Index">@Resource.MyShoppingCart <i class="fa-solid fa-cart-shopping"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Order" asp-action="Index">@Resource.MyOrders <i class="fa-solid fa-list"></i></a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Panel <i class="fa-solid fa-tools"></i></a>
                            </li>
                        }
                        else
                        {
                            if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Wishlist" asp-action="Index">Wishlist <i class="fa-solid fa-heart"></i></a>
                                </li>
                            }
                        }
                    </ul>

                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @if (Thread.CurrentThread.CurrentCulture.ToString() == "en")
                                {
                                    <span>English</span>
                                }
                                else
                                {
                                    <span>
                                        Български
                                    </span>
                                }
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="ChangeLanguage" asp-route-lang="en">English</a></li>
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="ChangeLanguage" asp-route-lang="bg">Bulgarian</a></li>
                            </ul>
                        </li>
                    </ul>

                    <form class="d-flex me-3" method="get" action="@Url.Action("Index", "Product")">
                        <div class="input-group">
                            <input class="form-control" type="search" placeholder="@Resource.SearchByBrand" name="searchTerm" value="@Context.Request.Query["searchTerm"]" aria-label="Search">
                            <button class="btn btn-light glass" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                        </div>
                    </form>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container text-white">
            &copy; @footerYear - OnlineShop.Web
        </div>
    </footer>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>